### PR TITLE
Bump dart version to 2.18.6

### PR DESCRIPTION
**Pull request by subzero911**
Should solve https://github.com/fluttertools/fvm/issues/474

### CODE REVIEW

**Comment by subzero911** [comment]
@leoafarias could you please set me as a maintainer?
If you ain't got no free minute to hit the "merge" button, I can do it for you.

**Comment by leoafarias** [comment]
> @leoafarias could you please set me as a maintainer? If you ain't got no free minute to hit the "merge" button, I can do it for you.

Sorry for the delay, the action never completed, I am running again, and will merge

**Comment by leoafarias** [comment]
@subzero911 We will have to see why this window CI is not finishing before merging

**Comment by subzero911** [comment]
image
there's something wrong with Windows platform

**Comment by leoafarias** [comment]
Don't think this is a proper fix, to what we are seeing on #474, will close this for now.

**Pull request closed without merging**
