### PR TITLE
Use Process.start instead of ProcessManager.spawn

### LINKED ISSUE #202: [Enhancement] No colors or formatting when using fvm flutter proxy
**Describe the bug**

When running commands through fvm (like `flutter test` or `flutter analyze`) it cuts off the formatting like color and caret manipulation what makes the output much harder to read than without fvm.

This is especially annoying when I have big output or many tests and I can't see what tests failed because it's already way beyond my terminal scroll buffer.

fvm-error

```
➜  ~/Projects  dart --version
Dart SDK version: 2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
➜  ~/Projects  fvm version
1.3.6
```

**Additional context**
I love fvm!

### PR DESCRIPTION
**Pull request by kuhnroyal**
This seems to work well in CLI with ANSI support.
I am not completely sure about non-CLI support.
The `ProcessManager` does a couple things under in regard to forwarding stdio but I can't get it to work correctly.
I don't see any problem with doing this manually instead.

Hopefully closes #202

### CODE REVIEW

**Comment by gaetschwartz** [comment]
Any update on this PR  ? : )

**Review by leoafarias — APPROVED** [review]
LGTM

**Comment by shilangyu** [comment]
Can we get a new FVM version released with this change?

**Comment by ManuelRauber** [comment]
@leoafarias Would be nice to have this update :)

**Comment by kuhnroyal** [comment]
Installed the 3.0.0-beta.1 and this works now.

**Pull request merged**
